### ISSUE TITLE
Version 5.15.0 not tagged

### ISSUE THREAD

**Issue by EggYoke** [BlinkID/blinkid-swift-package#6]
I see that the `main` branch sports the `5.15.0` version from "https://github.com/BlinkID/blinkid-ios".
That said, it seems the `5.15.0` tag has not yet been created.
It would help with Package Manager instead of having to target the `release/5.15.0` branch that may disappear at some point.

Cheers!

**Comment by mijo-gracanin** [comment]
Hey @EggYoke , thanks for letting us know! 🍻
The v5.15.0 is now released correctly!
